### ISSUE TITLE
Implement the `all-contributors` specification

### ISSUE THREAD

**Issue by MM-coder** [MattIBM/discord-wilfred#17]
Using the https://allcontributors.org/ bot, implement the all contributors specification. 

Example: https://github.com/MM-coder/coronavirus-wallpaper

**Comment by MattIBM** [comment]
This seems like a pain in the neck to be honest. I don't like the fact that it requires merges every time there's a new contributor, merge conflicts everywhere! This isn't meant to be a seriously big open-source project so I don't really see a need for this.

**Comment by MM-coder** [comment]
Fair enough
