### ISSUE TITLE
Make all command outputs common

### ISSUE THREAD

**Issue by MattIBM** [MattIBM/discord-wilfred#5]
Currently different commands output with different formats. Commands that output in a non-embed format should follow the same conventions as used by !economy and !xp

**Comment by MM-coder** [comment]
Working on this atm

**Comment by MM-coder** [comment]
Should I standardize error embeds? Maybe by providing an Error function that creates an embed?

**Comment by MattIBM** [comment]
Some errors do use an embed and some don't. My preference with errors is to not use an Embed because sometimes sending an embed is the issue.

Standard convention should be:
**Error**: <Error Message>

**Comment by MM-coder** [comment]
> 
> 
> Some errors do use an embed and some don't. My preference with errors is to not use an Embed because sometimes sending an embed is the issue.
> 
> Standard convention should be:
> **Error**: Error Message

Please note that I standardized embed errors in shop, since these are purley ascetical

**Comment by MM-coder** [comment]
@MattIBM can we keep this one open, in case something pops up that I might of missed?

P.S Assign

**Comment by MattIBM** [comment]
I believe there is a few other things that don't follow normal convention

**Comment by MM-coder** [comment]
I'll take a look

**Comment by MattIBM** [comment]
Implemented in 352
